version: '3'

services:
  app:
    image: diogo.santos/app:prod
    build: 
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  nginx:
    image: diogo.santos/nginx:prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    restart: always
    networks:
      - node-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initializer/create_table.sql:/docker-entrypoint-initdb.d/0_init.sql

networks:
  node-network:
    driver: bridge